apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: pyconjp-locust
build:
  artifacts:
  - image: tatchnicolas/pyconjp2021-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: kind-pyconjp2021-locust
  kubectl:
    manifests:
    - manifests/master.yaml
    - manifests/worker.yaml
    - manifests/sample_app.yaml
    - manifests/database.yaml
portForward:
- resourceType: service
  resourceName: sample-app-svc
  port: 8000
  localPort: 8000
- resourceType: service
  resourceName: locust-result-svc
  port: 8080
  localPort: 8080
