apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: pyconjp--locust
build:
  artifacts:
  - image: tatchnicolas/pyconjp2021-app
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/master.yaml
    - manifests/webserver.yaml
    - manifests/worker.yaml
portForward:
- resourceType: service
  resourceName: sample-app-svc
  port: 8000
  localPort: 8000
