apiVersion: batch/v1
kind: Job
metadata:
  name: locust-master
  labels:
    app: locust
    role: master
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      restartPolicy: OnFailure
      containers:
      - name: locust
        image: tatchnicolas/pyconjp2021-app
        command: ["locust", "--master", "--config", "/var/locust/locust.conf"]
        ports:
        - containerPort: 5557
        volumeMounts:
        - mountPath: /var/locust/
          readOnly: true
          name: locust-conf
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
      volumes:
      - name: locust-conf
        configMap:
          name: locust-master-conf
---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-svc
spec:
  selector:
    app: locust
    role: master
  ports:
    - protocol: TCP
      port: 5557
      targetPort: 5557
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-master-conf
data:
  locust.conf: |
    headless = true
    expect-workers = 2
    locustfile = ./locustfile.py
    host = http://sample-app-svc:8000
    users = 50
    spawn-rate = 10
    run-time = 1m
