apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: app
        image: tatchnicolas/pyconjp2021-app
        env:
        - name: APP_MONGO_URL
          value: mongodb://root:example@mongo-svc:27017/loadtest?authSource=admin
        - name: APP_MONGO_USER_COL  
          value: users
        command: ["uvicorn", "sample:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
