apiVersion: batch/v1
kind: Job
metadata:
  name: locust-worker
  labels:
    app: locust
    role: worker
spec:
  completions: 5
  parallelism: 5
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      restartPolicy: OnFailure
      containers:
      - name: locust
        image: tatchnicolas/pyconjp2021-app
        command: ["locust", "--worker"]
        env:
          - name: LOCUST_MASTER_NODE_HOST
            value: locust-master-svc
          - name: APP_MONGO_URL
            value: mongodb://root:example@mongo-svc:27017/local?authSource=admin
          - name: APP_MONGO_USER_COL  
            value: users
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
