apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust
    role: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
      - name: locust
        image: tatchnicolas/pyconjp2021-app
        command: ["--worker", "-f", "locustfile.py"]
        env:
          - name: LOCUST_LOCUSTFILE
            value: locustfile.py
          - name: LOCUST_MASTER_NODE_HOST
            value: locust-master-svc
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
