apiVersion: batch/v1
kind: Job
metadata:
  name: locust-worker
  labels:
    app: locust
    role: worker
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      restartPolicy: OnFailure
      containers:
      - name: locust
        image: tatchnicolas/pyconjp2021-app
        command: ["locust", "--worker"]
        env:
          - name: LOCUST_MASTER_NODE_HOST
            value: locust-master-svc
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 500m
